title: Casafeliz
email: shiroku.72@daum.net
description: Home Page of My Lovely Pet Lucky
baseurl: ''
url: 'https://casafeliz.github.io'
twitter_username: shiroku
github_username: casafeliz
theme: minima
plugins:
  - jekyll-feed
