# setup
title: Schuna Blog Post
tagline: '~lucky~'
email: shiroku.72@daum.net
description: 파이선 관련 스터디 내용과 럭키의 귀여운 사진들!
baseurl: ''
url: 'https://schuna.github.io'
github_username: schuna
paginate: 5
permalink: pretty
excerpt_separator: <!--more-->
future: true

# about / contact
author:
  name: schuna
  url: https://schuna.github.io/
  email: shiroku.72@daum.net


plugins:
  - jekyll-paginate

# Custom vars
version: 0.0.1
github:
  repo: https://github.com/schuna/schuna.github.io.git
  url: https://github.com/schuna/schuna.github.io/tree/master/